#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

if command -v "systemctl" > /dev/null 2>&1; then
	eval $(systemctl --user show-environment | grep SSH_AUTH_SOCK)
	export SSH_AUTH_SOCK
fi
