#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias l='ls -AlFh'
alias memusg='ps -eo rss,pid,comm,args | sort -n'
alias rmbak='find . -name "*~" -delete -print'
alias usage='du -sh [A-z]** | sort -n'
alias drmi='docker rmi $(docker images -q --filter "dangling=true")'
alias lns='ss -estp'
alias gno='xdg-open'
alias doc='docker-compose'
function jql() {
    jq '.' "$1" | less
}
if [[ -n "$DISPLAY" ]] && command -v setxkbmap >/dev/null; then
    setxkbmap -option caps:none
fi
